table olist_customers_dataset
	lineageTag: 14adb862-84a5-453e-8bff-feeb4997f56c

	column customer_id
		dataType: string
		lineageTag: 0d9ccce0-136d-4934-bf46-346a4f634b76
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_unique_id
		dataType: string
		lineageTag: 8dbbcce1-043e-457d-91e2-4ab35f9e3e10
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: 13dd6cf2-89f2-4322-a548-13a8b6c9eaed
		summarizeBy: sum
		sourceColumn: customer_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 13814134-ea53-42a2-82ce-83f31f9cf370
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 2e5b6fa7-a057-40e1-b301-f2f63143419c
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	partition olist_customers_dataset = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Study\Data Analytics Programme\Final Project\olist_customers_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", type text}, {"customer_unique_id", type text}, {"customer_zip_code_prefix", Int64.Type}, {"customer_city", type text}, {"customer_state", type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"customer_unique_id"}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Removed Duplicates",{{"customer_city", Text.Proper, type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Capitalized Each Word",{{"customer_city", Text.Trim, type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"customer_city", Text.Clean, type text}}),
				    #"Trimmed Text1" = Table.TransformColumns(#"Cleaned Text",{{"customer_state", Text.Trim, type text}}),
				    #"Cleaned Text1" = Table.TransformColumns(#"Trimmed Text1",{{"customer_state", Text.Clean, type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Cleaned Text1", each true),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [customer_unique_id] <> null and [customer_unique_id] <> ""),
				    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows1", each [customer_id] <> null and [customer_id] <> ""),
				    #"Trimmed Text2" = Table.TransformColumns(#"Filtered Rows2",{{"customer_city", Text.Trim, type text}}),
				    #"Cleaned Text2" = Table.TransformColumns(#"Trimmed Text2",{{"customer_city", Text.Clean, type text}})
				in
				    #"Cleaned Text2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

